fix indent levels because ocd

diff --git a/make-repo b/make-repo
--- a/make-repo
+++ b/make-repo
@@ -14,13 +14,6 @@ DEFINE_string 'repo_name' '' 'Set the name for the repo to be created on github 
 DEFINE_boolean 'remote_link' false 'Link the created remote repo to the repo in the current working directory' 'r'
 DEFINE_string 'github_user' '' 'Your github username (Required)' 'u'
 
-die()
-{
-  [ $# -gt 0 ] && echo "error: $@" >&2
-  flags_help
-  exit 1
-}
-
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 
@@ -38,11 +31,11 @@ if [ "${FLAGS_github_user}" == '' ]
   else
   if [ "${FLAGS_repo_name}" == '' ]
     then
-      echo 'Required Field missing: Repo Name (USAGE: make-repo -n "repo-name" -u "github-username" -[pr])'
-      exit 1
+    echo 'Required Field missing: Repo Name (USAGE: make-repo -n "repo-name" -u "github-username" -[pr])'
+    exit 1
     else
-      repo_name="${FLAGS_repo_name}"
-      github_user="${FLAGS_github_user}"
+    repo_name="${FLAGS_repo_name}"
+    github_user="${FLAGS_github_user}"
   fi
 fi
 
@@ -56,9 +49,9 @@ echo "Repo created at: ${RESPONSE}"
 
 if [ "${FLAGS_remote_link}" == 0 ]
   then
-    REMOTE_ADD="git remote add origin \"${RESPONSE}\""
-    eval "$REMOTE_ADD"
-    echo "Remote added, use git push -u origin master to push your local repo to github"
+  REMOTE_ADD="git remote add origin \"${RESPONSE}\""
+  eval "$REMOTE_ADD"
+  echo "Remote added, use git push -u origin master to push your local repo to github"
   else
-    exit 0
+  exit 0
 fi
